source = ~/.config/hypr/themes/current.conf


general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $base
    path = ~/Pictures/current
    blur_passes = 3
}

input-field {
    monitor =
    size = 650, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $base    
    outer_color = $green
    outline_thickness = 4

    font_family = FantasqueSansM Nerd Font
    font_color = $text

    placeholder_text = Enter Password
    check_color = $green
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    fail_color = $red

    rounding = 25 
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
